/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tio;

import com.s.DataPengiriman;
import com.s.PersonPenerima;
import com.s.PersonPengirim;
import com.s.TarifFile;
import com.s.TarifFileDao;
import com.sun.glass.events.KeyEvent;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Main extends javax.swing.JFrame {
    PersonPenerima personpenerima = new PersonPenerima();
    PersonPengirim personpengirim = new PersonPengirim();
    DataPengiriman datapengiriman = new DataPengiriman();
    DecimalFormat df = new DecimalFormat("###,###.##");
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    
    public Main() {
        initComponents();
        koTuPengirimanTextField.setEnabled(false);
        HargaTotalLabel.setVisible(false);
            hargaPengirimanLabel.setVisible(false);
            hargaAsuransiLabel.setVisible(false);
            hargaBrgPengirimanTextField.setText("0"); 
            hargaBrgPengirimanTextField.setEnabled(false);
            tglPengirimanLabel.setVisible(false);
            hasilNomorPaketLabel.setVisible(false);
            nomorPaketPengirimanTextField.setEnabled(false);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        panjangBrgPengirimanTextField = new javax.swing.JTextField();
        lebarBrgPengirimanTextField = new javax.swing.JTextField();
        tinggiBrgPengirimanTextField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jenisLayananPengirimanComboBox = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        hargaBrgPengirimanTextField = new javax.swing.JTextField();
        cashPengirimanRadioButton = new javax.swing.JRadioButton();
        debitPengirimanRadioButton = new javax.swing.JRadioButton();
        ccPengirimanRadioButton = new javax.swing.JRadioButton();
        asuransiYaPengirimanRadioButton = new javax.swing.JRadioButton();
        asuransiNoPengirimanRadioButton = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        nomorPaketPengirimanTextField = new javax.swing.JTextField();
        koTuPengirimanTextField = new javax.swing.JTextField();
        jenisBrgPengirimanTextField = new javax.swing.JTextField();
        beratBarangPengirimanTextField = new javax.swing.JTextField();
        kirimButton = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        totalBayayLabel = new javax.swing.JLabel();
        HargaTotalLabel = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        hargaPengirimanLabel = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        hargaAsuransiLabel = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        tglPengirimanLabel = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        hasilNomorPaketLabel = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        tglKirimPengirimanDateChooser = new com.toedter.calendar.JDateChooser();
        clearButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        provinsiPengirimCombobox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        provinsiPenerimaComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        NamaPengirimTextfield = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        telpPenerimaTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        telpPengirimTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        kodePosPenerimaTextField = new javax.swing.JTextField();
        kodePosPengirimTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatPenerimaTextfield = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamatPengirimTextField = new javax.swing.JTextArea();
        namaPenerimaTextField = new javax.swing.JTextField();
        kotaPengirimComboBox = new javax.swing.JComboBox<>();
        kotaPenerimaComboBox = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(0, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel13.setText("Data Pengiriman");

        jLabel15.setText("Nomor Paket");

        jLabel16.setText("Kota Tujuan");

        jLabel17.setText("Jenis Barang");

        jLabel18.setText("Berat Barang");

        jLabel19.setText("Tanggal Kirim");

        jLabel20.setText("Dimensi");

        jLabel21.setText("Panjang");

        jLabel22.setText("Lebar");

        jLabel23.setText("Tinggi");

        jLabel24.setText(":");

        panjangBrgPengirimanTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panjangBrgPengirimanTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                panjangBrgPengirimanTextFieldKeyTyped(evt);
            }
        });

        lebarBrgPengirimanTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lebarBrgPengirimanTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lebarBrgPengirimanTextFieldKeyTyped(evt);
            }
        });

        tinggiBrgPengirimanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinggiBrgPengirimanTextFieldActionPerformed(evt);
            }
        });
        tinggiBrgPengirimanTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tinggiBrgPengirimanTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tinggiBrgPengirimanTextFieldKeyTyped(evt);
            }
        });

        jLabel25.setText("Jenis Layanan");

        jenisLayananPengirimanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "REGULAR", "KILAT", "SDS", "ONS", "HDS" }));
        jenisLayananPengirimanComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisLayananPengirimanComboBoxActionPerformed(evt);
            }
        });

        jLabel26.setText("Asuransi");

        jLabel27.setText("Harga Barang");

        jLabel28.setText("Pembayaran");

        hargaBrgPengirimanTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                hargaBrgPengirimanTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hargaBrgPengirimanTextFieldKeyTyped(evt);
            }
        });

        cashPengirimanRadioButton.setText("Cash");
        cashPengirimanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashPengirimanRadioButtonActionPerformed(evt);
            }
        });

        debitPengirimanRadioButton.setText("Debit");
        debitPengirimanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debitPengirimanRadioButtonActionPerformed(evt);
            }
        });

        ccPengirimanRadioButton.setText("CC");
        ccPengirimanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccPengirimanRadioButtonActionPerformed(evt);
            }
        });

        asuransiYaPengirimanRadioButton.setText("Ya");
        asuransiYaPengirimanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asuransiYaPengirimanRadioButtonActionPerformed(evt);
            }
        });

        asuransiNoPengirimanRadioButton.setText("Tidak");
        asuransiNoPengirimanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asuransiNoPengirimanRadioButtonActionPerformed(evt);
            }
        });

        jLabel30.setText(":");

        jLabel31.setText(":");

        jLabel32.setText(":");

        nomorPaketPengirimanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomorPaketPengirimanTextFieldActionPerformed(evt);
            }
        });
        nomorPaketPengirimanTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomorPaketPengirimanTextFieldKeyTyped(evt);
            }
        });

        koTuPengirimanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                koTuPengirimanTextFieldActionPerformed(evt);
            }
        });

        beratBarangPengirimanTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                beratBarangPengirimanTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                beratBarangPengirimanTextFieldKeyTyped(evt);
            }
        });

        kirimButton.setText("KIRIM CUSSSS");
        kirimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kirimButtonActionPerformed(evt);
            }
        });

        jLabel34.setText(":");

        jLabel35.setText(":");

        jLabel36.setText(":");

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel29.setText("TOTAL YANG HARUS DIBAYAR");

        totalBayayLabel.setText("RP.");

        HargaTotalLabel.setText("jLabel33");

        jLabel33.setText("HARGA PENGIRIMAN");

        jLabel40.setText("RP.");

        hargaPengirimanLabel.setText("jLabel41");

        jLabel42.setText("HARGA ASURANSI");

        jLabel43.setText("RP.");

        hargaAsuransiLabel.setText("jLabel44");

        jLabel41.setText("TANGGAL PENGIRIMAN");

        tglPengirimanLabel.setText("jLabel44");

        jLabel44.setText("NOMOR PAKET");

        hasilNomorPaketLabel.setText("jLabel45");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(totalBayayLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HargaTotalLabel))
                    .addComponent(jLabel29)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hargaPengirimanLabel))
                            .addComponent(jLabel42)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel43)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hargaAsuransiLabel)))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hasilNomorPaketLabel)
                            .addComponent(jLabel44)
                            .addComponent(tglPengirimanLabel)
                            .addComponent(jLabel41))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(hargaPengirimanLabel)
                    .addComponent(tglPengirimanLabel))
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(jLabel44))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hargaAsuransiLabel)
                    .addComponent(jLabel43)
                    .addComponent(hasilNomorPaketLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HargaTotalLabel)
                    .addComponent(totalBayayLabel)))
        );

        jLabel37.setText(":");

        jLabel38.setText(":");

        jLabel39.setText(":");

        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel26))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(asuransiYaPengirimanRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(asuransiNoPengirimanRadioButton)
                                .addGap(101, 101, 101))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel30)
                                        .addGap(47, 47, 47)
                                        .addComponent(jenisLayananPengirimanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(41, 41, 41)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel22)
                                                    .addComponent(jLabel21)
                                                    .addComponent(jLabel23))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lebarBrgPengirimanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(panjangBrgPengirimanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tinggiBrgPengirimanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jenisBrgPengirimanTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                                .addComponent(beratBarangPengirimanTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(koTuPengirimanTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(nomorPaketPengirimanTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(tglKirimPengirimanDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel32)
                                                .addGap(43, 43, 43)
                                                .addComponent(cashPengirimanRadioButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(debitPengirimanRadioButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ccPengirimanRadioButton))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(39, 39, 39)
                                                        .addComponent(hargaBrgPengirimanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(kirimButton)
                                                .addGap(40, 40, 40)
                                                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel27))
                                .addGap(63, 63, 63))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(nomorPaketPengirimanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jLabel38))
                    .addComponent(koTuPengirimanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jLabel36))
                    .addComponent(jenisBrgPengirimanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(beratBarangPengirimanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jLabel34))
                    .addComponent(tglKirimPengirimanDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel24)
                    .addComponent(jLabel21)
                    .addComponent(panjangBrgPengirimanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(lebarBrgPengirimanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tinggiBrgPengirimanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisLayananPengirimanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel30))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jLabel37))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jLabel31))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(jLabel28)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(asuransiYaPengirimanRadioButton)
                            .addComponent(asuransiNoPengirimanRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hargaBrgPengirimanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cashPengirimanRadioButton)
                            .addComponent(debitPengirimanRadioButton)
                            .addComponent(ccPengirimanRadioButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kirimButton)
                    .addComponent(clearButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(0, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("Identitas");

        jLabel2.setText("Nama Pengirim ");

        jLabel3.setText("Alamat Pengirim");

        jLabel4.setText("Kota");

        jLabel5.setText("Kode Pos");

        provinsiPengirimCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DKI JAKARTA" }));

        jLabel6.setText("Telepon");

        jLabel7.setText("Nama Penerima");

        jLabel8.setText("Alamat Penerima");

        jLabel9.setText("Kota");

        provinsiPenerimaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--PILIHAN--", "DKI JAKARTA", "BANTEN", "JAWA BARAT" }));
        provinsiPenerimaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinsiPenerimaComboBoxActionPerformed(evt);
            }
        });

        jLabel11.setText("Telepon");

        NamaPengirimTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaPengirimTextfieldActionPerformed(evt);
            }
        });

        jLabel12.setText("Provinsi");

        telpPenerimaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telpPenerimaTextFieldActionPerformed(evt);
            }
        });
        telpPenerimaTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telpPenerimaTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telpPenerimaTextFieldKeyTyped(evt);
            }
        });

        jLabel14.setText("Provinsi");

        telpPengirimTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telpPengirimTextFieldActionPerformed(evt);
            }
        });
        telpPengirimTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telpPengirimTextFieldKeyTyped(evt);
            }
        });

        jLabel10.setText("Kode Pos");

        kodePosPenerimaTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kodePosPenerimaTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kodePosPenerimaTextFieldKeyTyped(evt);
            }
        });

        kodePosPengirimTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodePosPengirimTextFieldActionPerformed(evt);
            }
        });
        kodePosPengirimTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kodePosPengirimTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kodePosPengirimTextFieldKeyTyped(evt);
            }
        });

        alamatPenerimaTextfield.setColumns(20);
        alamatPenerimaTextfield.setRows(5);
        jScrollPane1.setViewportView(alamatPenerimaTextfield);

        alamatPengirimTextField.setColumns(20);
        alamatPengirimTextField.setRows(5);
        jScrollPane2.setViewportView(alamatPengirimTextField);

        kotaPengirimComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JAKARTA" }));

        kotaPenerimaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        kotaPenerimaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kotaPenerimaComboBoxActionPerformed(evt);
            }
        });

        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10))
                                .addGap(89, 89, 89)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(kotaPengirimComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 166, Short.MAX_VALUE)
                                        .addComponent(provinsiPengirimCombobox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(kodePosPengirimTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(telpPengirimTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(namaPenerimaTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(kotaPenerimaComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 166, Short.MAX_VALUE)
                                        .addComponent(telpPenerimaTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(kodePosPenerimaTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(provinsiPenerimaComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(NamaPengirimTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NamaPengirimTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(provinsiPengirimCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kotaPengirimComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(kodePosPengirimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(telpPengirimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(namaPenerimaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(provinsiPenerimaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(kotaPenerimaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(kodePosPenerimaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(telpPenerimaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NamaPengirimTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaPengirimTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaPengirimTextfieldActionPerformed

    private void kirimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kirimButtonActionPerformed
       try{
        personpengirim.setNama(NamaPengirimTextfield.getText());
        personpengirim.setAlamat(alamatPengirimTextField.getText());
        personpengirim.setProvinsi(provinsiPengirimCombobox.getSelectedItem().toString());
        personpengirim.setKotaPengirim(kotaPengirimComboBox.getSelectedItem().toString());
        personpengirim.setKodeposPengirim(Integer.parseInt(kodePosPengirimTextField.getText()));
        personpengirim.setTelpPengirim(Integer.parseInt(telpPengirimTextField.getText()));
        
        
        personpenerima.setNama(namaPenerimaTextField.getText());
        personpenerima.setAlamat(alamatPengirimTextField.getText());
        personpenerima.setProvinsi(provinsiPenerimaComboBox.getSelectedItem().toString());
        personpenerima.setKotaPenerima(kotaPenerimaComboBox.getSelectedItem().toString());
        personpenerima.setKodeposPenerima(Integer.parseInt(kodePosPenerimaTextField.getText()));
        personpenerima.setTelpPenerima(Integer.parseInt(telpPenerimaTextField.getText()));
        
        //datapengiriman.setNomorpaket(Double.parseDouble(nomorPaketPengirimanTextField.getText()));
        datapengiriman.setKotatujuan(koTuPengirimanTextField.getText());
        datapengiriman.setJenisbarang(jenisBrgPengirimanTextField.getText());
        datapengiriman.setBeratbarang(Integer.parseInt(beratBarangPengirimanTextField.getText()));
        datapengiriman.setTanggalkirim(tglKirimPengirimanDateChooser.getDate());
        datapengiriman.setPanjang(Integer.parseInt(panjangBrgPengirimanTextField.getText()));
        datapengiriman.setLebar(Integer.parseInt(lebarBrgPengirimanTextField.getText()));
        datapengiriman.setTinggi(Integer.parseInt(tinggiBrgPengirimanTextField.getText()));
        datapengiriman.setJenislayanan(jenisLayananPengirimanComboBox.getSelectedItem().toString());
 
        if(asuransiYaPengirimanRadioButton.isSelected()){
            datapengiriman.setAsuransi(true);
         
        }
        else if(asuransiNoPengirimanRadioButton.isSelected()){
            datapengiriman.setAsuransi(false);
        }
        datapengiriman.setHargabarang(Integer.parseInt(hargaBrgPengirimanTextField.getText()));
       
        if(cashPengirimanRadioButton.isSelected()){
            datapengiriman.setPembayaran(cashPengirimanRadioButton.getText());
        }
        else if(debitPengirimanRadioButton.isSelected()){
            datapengiriman.setPembayaran(debitPengirimanRadioButton.getText());
        }
        else if(ccPengirimanRadioButton.isSelected()){
            datapengiriman.setPembayaran(debitPengirimanRadioButton.getText());
        }
        
        
        if(jenisLayananPengirimanComboBox.getSelectedItem().toString().equalsIgnoreCase("REGULAR")){
            datapengiriman.setNilaiasuransi();
            datapengiriman.getHargaRegular();
            datapengiriman.setHargaAwalKaliBerat();
            datapengiriman.setHargaPlusAsuransi();
            
            HargaTotalLabel.setText(""+df.format(datapengiriman.getHargaPlusAsuransi()));
            hargaPengirimanLabel.setText(""+df.format(datapengiriman.getHargaAwalKaliBerat()));
            hargaAsuransiLabel.setText(""+df.format(datapengiriman.getNilaiasuransi()));
            tglPengirimanLabel.setText(""+sdf.format(datapengiriman.getTanggalkirim()));
         
            
            
        HargaTotalLabel.setVisible(true);
            hargaPengirimanLabel.setVisible(true);
            hargaAsuransiLabel.setVisible(true);
            tglPengirimanLabel.setVisible(true);
            hasilNomorPaketLabel.setVisible(true);
        }
        
        else if (jenisLayananPengirimanComboBox.getSelectedItem().toString().equalsIgnoreCase("KILAT")){
            datapengiriman.setNilaiasuransi();
            datapengiriman.getHargaKilat();
            datapengiriman.setHargaAwalKaliBerat();
            datapengiriman.setHargaPlusAsuransi();
            
            HargaTotalLabel.setText(""+df.format(datapengiriman.getHargaPlusAsuransi()));
            hargaPengirimanLabel.setText(""+df.format(datapengiriman.getHargaAwalKaliBerat()));
            hargaAsuransiLabel.setText(""+df.format(datapengiriman.getNilaiasuransi()));
            tglPengirimanLabel.setText(""+sdf.format(datapengiriman.getTanggalkirim()));
            
        HargaTotalLabel.setVisible(true);
            hargaPengirimanLabel.setVisible(true);
            hargaAsuransiLabel.setVisible(true);
            tglPengirimanLabel.setVisible(true);
            hasilNomorPaketLabel.setVisible(true);
        }
        
        else if (jenisLayananPengirimanComboBox.getSelectedItem().toString().equalsIgnoreCase("SDS")){
            datapengiriman.setNilaiasuransi();
            datapengiriman.getHargaSds();
            datapengiriman.setHargaAwalKaliBerat();
            datapengiriman.setHargaPlusAsuransi();
            
            HargaTotalLabel.setText(""+df.format(datapengiriman.getHargaPlusAsuransi()));
            hargaPengirimanLabel.setText(""+df.format(datapengiriman.getHargaAwalKaliBerat()));
            hargaAsuransiLabel.setText(""+df.format(datapengiriman.getNilaiasuransi()));
            tglPengirimanLabel.setText(""+sdf.format(datapengiriman.getTanggalkirim()));
            
        HargaTotalLabel.setVisible(true);
            hargaPengirimanLabel.setVisible(true);
            hargaAsuransiLabel.setVisible(true);
            tglPengirimanLabel.setVisible(true);
            hasilNomorPaketLabel.setVisible(true);
            
        }
        
        else if (jenisLayananPengirimanComboBox.getSelectedItem().toString().equalsIgnoreCase("ONS")){
            datapengiriman.setNilaiasuransi();
            datapengiriman.getHargaOns();
            datapengiriman.setHargaAwalKaliBerat();
            datapengiriman.setHargaPlusAsuransi();
            
            HargaTotalLabel.setText(""+df.format(datapengiriman.getHargaPlusAsuransi()));
            hargaPengirimanLabel.setText(""+df.format(datapengiriman.getHargaAwalKaliBerat()));
            hargaAsuransiLabel.setText(""+df.format(datapengiriman.getNilaiasuransi()));
            tglPengirimanLabel.setText(""+sdf.format(datapengiriman.getTanggalkirim()));
            
        HargaTotalLabel.setVisible(true);
            hargaPengirimanLabel.setVisible(true);
            hargaAsuransiLabel.setVisible(true);
            tglPengirimanLabel.setVisible(true);
            hasilNomorPaketLabel.setVisible(true);
        }
        
        
        else if (jenisLayananPengirimanComboBox.getSelectedItem().toString().equalsIgnoreCase("HDS")){
            datapengiriman.setNilaiasuransi();
            datapengiriman.getHargaHds();
            datapengiriman.setHargaAwalKaliBerat();
            datapengiriman.setHargaPlusAsuransi();
            
            HargaTotalLabel.setText(""+df.format(datapengiriman.getHargaPlusAsuransi()));
            hargaPengirimanLabel.setText(""+df.format(datapengiriman.getHargaAwalKaliBerat()));
            hargaAsuransiLabel.setText(""+df.format(datapengiriman.getNilaiasuransi()));
            tglPengirimanLabel.setText(""+sdf.format(datapengiriman.getTanggalkirim()));
            
        HargaTotalLabel.setVisible(true);
            hargaPengirimanLabel.setVisible(true);
            hargaAsuransiLabel.setVisible(true);
            tglPengirimanLabel.setVisible(true);
            hasilNomorPaketLabel.setVisible(true);
        }
       }catch(Exception e){
           JOptionPane.showMessageDialog(rootPane, "DATA TIDAK BOLEH KOSONG");
       }
       nomorPaketPengirimanTextField.setText(DataPengiriman.getRandom());
       hasilNomorPaketLabel.setText(nomorPaketPengirimanTextField.getText());
       kirimButton.setEnabled(false);
       //angkaLabel.setText(""+total);
        
    }//GEN-LAST:event_kirimButtonActionPerformed

    private void tinggiBrgPengirimanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinggiBrgPengirimanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinggiBrgPengirimanTextFieldActionPerformed

    private void telpPenerimaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telpPenerimaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telpPenerimaTextFieldActionPerformed

    private void provinsiPenerimaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinsiPenerimaComboBoxActionPerformed
        if(String.valueOf(provinsiPenerimaComboBox.getSelectedItem()).equalsIgnoreCase("DKI JAKARTA")){
         kotaPenerimaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"JAKARTA BARAT", "JAKARTA TIMUR"
         ,"JAKARTA SELATAN", "JAKARTA UTARA"}));
          }
        else if (String.valueOf(provinsiPenerimaComboBox.getSelectedItem()).equalsIgnoreCase("BANTEN")){
            kotaPenerimaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"TANGERANG","RANGKASBITUNG", "PANDEGLANG",
            "SERANG"}));
        }
        else if(provinsiPenerimaComboBox.getSelectedItem().toString().equalsIgnoreCase("JAWA BARAT")){
        kotaPenerimaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"BANDUNG","BANDUNG BARAT", "KARAWANG",
            "KUNINGAN"})); 
        }
        else if(provinsiPenerimaComboBox.getSelectedItem().toString().equalsIgnoreCase("--PILIHAN--")){
            kotaPenerimaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""})); 
        }
    }//GEN-LAST:event_provinsiPenerimaComboBoxActionPerformed

    private void telpPengirimTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telpPengirimTextFieldKeyTyped
        char enter=evt.getKeyChar() ;
        
        if(!(Character.isDigit(enter) || enter == KeyEvent.VK_BACKSPACE))
        {            
            
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Harus Angka");
        }
        
    }//GEN-LAST:event_telpPengirimTextFieldKeyTyped

    private void kotaPenerimaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kotaPenerimaComboBoxActionPerformed
        // TODO add your handling code here:
        koTuPengirimanTextField.setText(kotaPenerimaComboBox.getSelectedItem().toString());
        
         
    }//GEN-LAST:event_kotaPenerimaComboBoxActionPerformed

    private void koTuPengirimanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_koTuPengirimanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_koTuPengirimanTextFieldActionPerformed

    private void nomorPaketPengirimanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomorPaketPengirimanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomorPaketPengirimanTextFieldActionPerformed

    private void asuransiYaPengirimanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asuransiYaPengirimanRadioButtonActionPerformed
         asuransiNoPengirimanRadioButton.setSelected(false);
         hargaBrgPengirimanTextField.setEnabled(true);
    }//GEN-LAST:event_asuransiYaPengirimanRadioButtonActionPerformed

    private void asuransiNoPengirimanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asuransiNoPengirimanRadioButtonActionPerformed
         asuransiYaPengirimanRadioButton.setSelected(false);
         hargaBrgPengirimanTextField.setEnabled(false);
         hargaBrgPengirimanTextField.setText("0");
    }//GEN-LAST:event_asuransiNoPengirimanRadioButtonActionPerformed

    private void cashPengirimanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashPengirimanRadioButtonActionPerformed
        // TODO add your handling code here:debit
        debitPengirimanRadioButton.setSelected(false);
        ccPengirimanRadioButton.setSelected(false);
        
    }//GEN-LAST:event_cashPengirimanRadioButtonActionPerformed

    private void debitPengirimanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debitPengirimanRadioButtonActionPerformed
        // TODO add your handling code here:
        cashPengirimanRadioButton.setSelected(false);
        ccPengirimanRadioButton.setSelected(false);
    }//GEN-LAST:event_debitPengirimanRadioButtonActionPerformed

    private void ccPengirimanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccPengirimanRadioButtonActionPerformed
        // TODO add your handling code here:
        debitPengirimanRadioButton.setSelected(false);
        cashPengirimanRadioButton.setSelected(false);
    }//GEN-LAST:event_ccPengirimanRadioButtonActionPerformed

    private void telpPengirimTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telpPengirimTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telpPengirimTextFieldActionPerformed

    private void kodePosPengirimTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodePosPengirimTextFieldActionPerformed
      
    }//GEN-LAST:event_kodePosPengirimTextFieldActionPerformed

    private void kodePosPengirimTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kodePosPengirimTextFieldKeyPressed
    
        
    }//GEN-LAST:event_kodePosPengirimTextFieldKeyPressed

    private void kodePosPenerimaTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kodePosPenerimaTextFieldKeyPressed
 
    }//GEN-LAST:event_kodePosPenerimaTextFieldKeyPressed

    private void telpPenerimaTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telpPenerimaTextFieldKeyPressed
 
    }//GEN-LAST:event_telpPenerimaTextFieldKeyPressed

    private void beratBarangPengirimanTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_beratBarangPengirimanTextFieldKeyPressed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_beratBarangPengirimanTextFieldKeyPressed

    private void panjangBrgPengirimanTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panjangBrgPengirimanTextFieldKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_panjangBrgPengirimanTextFieldKeyPressed

    private void lebarBrgPengirimanTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lebarBrgPengirimanTextFieldKeyPressed
 
    }//GEN-LAST:event_lebarBrgPengirimanTextFieldKeyPressed

    private void tinggiBrgPengirimanTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tinggiBrgPengirimanTextFieldKeyPressed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_tinggiBrgPengirimanTextFieldKeyPressed

    private void hargaBrgPengirimanTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hargaBrgPengirimanTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaBrgPengirimanTextFieldKeyPressed

    private void kodePosPengirimTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kodePosPengirimTextFieldKeyTyped
        // TODO add your handling code here:
        char enter=evt.getKeyChar() ;
        
        if(!(Character.isDigit(enter) || enter == KeyEvent.VK_BACKSPACE))
        {            
            
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Harus Angka");
        }
    }//GEN-LAST:event_kodePosPengirimTextFieldKeyTyped

    private void kodePosPenerimaTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kodePosPenerimaTextFieldKeyTyped
        // TODO add your handling code here:
        char enter=evt.getKeyChar() ;
        
        if(!(Character.isDigit(enter) || enter == KeyEvent.VK_BACKSPACE))
        {            
            
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Harus Angka");
        }
    }//GEN-LAST:event_kodePosPenerimaTextFieldKeyTyped

    private void telpPenerimaTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telpPenerimaTextFieldKeyTyped
        // TODO add your handling code here:
        char enter=evt.getKeyChar() ;
        
        if(!(Character.isDigit(enter) || enter == KeyEvent.VK_BACKSPACE))
        {            
            
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Harus Angka");
        }
    }//GEN-LAST:event_telpPenerimaTextFieldKeyTyped

    private void beratBarangPengirimanTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_beratBarangPengirimanTextFieldKeyTyped
        // TODO add your handling code here:
        char enter=evt.getKeyChar() ;
        
        if(!(Character.isDigit(enter) || enter == KeyEvent.VK_BACKSPACE))
        {            
            
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Harus Angka");
        }
    }//GEN-LAST:event_beratBarangPengirimanTextFieldKeyTyped

    private void panjangBrgPengirimanTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panjangBrgPengirimanTextFieldKeyTyped
        // TODO add your handling code here:
        char enter=evt.getKeyChar() ;
        
        if(!(Character.isDigit(enter) || enter == KeyEvent.VK_BACKSPACE))
        {            
            
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Harus Angka");
        }
    }//GEN-LAST:event_panjangBrgPengirimanTextFieldKeyTyped

    private void lebarBrgPengirimanTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lebarBrgPengirimanTextFieldKeyTyped
        // TODO add your handling code here:
        char enter=evt.getKeyChar() ;
        
        if(!(Character.isDigit(enter) || enter == KeyEvent.VK_BACKSPACE))
        {            
            
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Harus Angka");
        }
    }//GEN-LAST:event_lebarBrgPengirimanTextFieldKeyTyped

    private void tinggiBrgPengirimanTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tinggiBrgPengirimanTextFieldKeyTyped
        // TODO add your handling code here:
        char enter=evt.getKeyChar() ;
        
        if(!(Character.isDigit(enter) || enter == KeyEvent.VK_BACKSPACE))
        {            
            
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Harus Angka");
        }
    }//GEN-LAST:event_tinggiBrgPengirimanTextFieldKeyTyped

    private void hargaBrgPengirimanTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hargaBrgPengirimanTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaBrgPengirimanTextFieldKeyTyped

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        NamaPengirimTextfield.setText("");
        alamatPengirimTextField.setText("");
        kodePosPengirimTextField.setText("");
        telpPengirimTextField.setText("");
        
        namaPenerimaTextField.setText("");
        alamatPenerimaTextfield.setText("");
        provinsiPenerimaComboBox.setSelectedItem("--PILIHAN--");
        kodePosPenerimaTextField.setText("");
        telpPenerimaTextField.setText("");
        
        nomorPaketPengirimanTextField.setText("");
        koTuPengirimanTextField.setText("");
        jenisBrgPengirimanTextField.setText("");
        beratBarangPengirimanTextField.setText("");
        tglKirimPengirimanDateChooser.setDate(null);
        panjangBrgPengirimanTextField.setText("");
        lebarBrgPengirimanTextField.setText("");
        tinggiBrgPengirimanTextField.setText("");
        jenisLayananPengirimanComboBox.setSelectedItem(null);
        asuransiNoPengirimanRadioButton.setSelected(false);
        asuransiYaPengirimanRadioButton.setSelected(false);
        hargaBrgPengirimanTextField.setText("");
        cashPengirimanRadioButton.setSelected(false);
        debitPengirimanRadioButton.setSelected(false);
        ccPengirimanRadioButton.setSelected(false);
        
        hargaPengirimanLabel.setText("");
        hargaAsuransiLabel.setText("");
        HargaTotalLabel.setText("");
        tglPengirimanLabel.setText("");
        hasilNomorPaketLabel.setText("");
        kirimButton.setEnabled(true);
        
    }//GEN-LAST:event_clearButtonActionPerformed

    private void jenisLayananPengirimanComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisLayananPengirimanComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisLayananPengirimanComboBoxActionPerformed

    private void nomorPaketPengirimanTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomorPaketPengirimanTextFieldKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        
        if(!(Character.isDigit(enter) || enter == KeyEvent.VK_BACKSPACE)){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Harus Angka");
        }
    }//GEN-LAST:event_nomorPaketPengirimanTextFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HargaTotalLabel;
    private javax.swing.JTextField NamaPengirimTextfield;
    private javax.swing.JTextArea alamatPenerimaTextfield;
    private javax.swing.JTextArea alamatPengirimTextField;
    private javax.swing.JRadioButton asuransiNoPengirimanRadioButton;
    private javax.swing.JRadioButton asuransiYaPengirimanRadioButton;
    private javax.swing.JTextField beratBarangPengirimanTextField;
    private javax.swing.JRadioButton cashPengirimanRadioButton;
    private javax.swing.JRadioButton ccPengirimanRadioButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JRadioButton debitPengirimanRadioButton;
    private javax.swing.JLabel hargaAsuransiLabel;
    private javax.swing.JTextField hargaBrgPengirimanTextField;
    private javax.swing.JLabel hargaPengirimanLabel;
    private javax.swing.JLabel hasilNomorPaketLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jenisBrgPengirimanTextField;
    private javax.swing.JComboBox<String> jenisLayananPengirimanComboBox;
    private javax.swing.JButton kirimButton;
    private javax.swing.JTextField koTuPengirimanTextField;
    private javax.swing.JTextField kodePosPenerimaTextField;
    private javax.swing.JTextField kodePosPengirimTextField;
    private javax.swing.JComboBox<String> kotaPenerimaComboBox;
    private javax.swing.JComboBox<String> kotaPengirimComboBox;
    private javax.swing.JTextField lebarBrgPengirimanTextField;
    private javax.swing.JTextField namaPenerimaTextField;
    private javax.swing.JTextField nomorPaketPengirimanTextField;
    private javax.swing.JTextField panjangBrgPengirimanTextField;
    private javax.swing.JComboBox<String> provinsiPenerimaComboBox;
    private javax.swing.JComboBox<String> provinsiPengirimCombobox;
    private javax.swing.JTextField telpPenerimaTextField;
    private javax.swing.JTextField telpPengirimTextField;
    private com.toedter.calendar.JDateChooser tglKirimPengirimanDateChooser;
    private javax.swing.JLabel tglPengirimanLabel;
    private javax.swing.JTextField tinggiBrgPengirimanTextField;
    private javax.swing.JLabel totalBayayLabel;
    // End of variables declaration//GEN-END:variables
}
